export interface CategoryGroup {
	name: string;
	color: string;
	patterns: readonly string[];
}

export const CATEGORY_GROUPS: readonly CategoryGroup[] = [
	{
		name: "Homonymie",
		color: "#94a3b8",
		patterns: ["homonymie", "wikimédia", "wikimedia"],
	},
	{
		name: "Listes",
		color: "#cbd5e1",
		patterns: ["liste"],
	},
	{
		name: "Politique",
		color: "#3b82f6",
		patterns: [
			"homme politique",
			"femme politique",
			"personnalité politique",
			"homme état",
			"chef état",
			"politique",
			"politicien*",
			"président",
			"présidente",
			"ministre",
			"député*",
			"maire",
			"sénat*",
			"diplomate",
			"parti",
			"syndicaliste",
		],
	},
	{
		name: "Noblesse & royauté",
		color: "#eab308",
		patterns: [
			"roi",
			"reine",
			"prince",
			"princesse",
			"duc",
			"duchesse",
			"comte",
			"comtesse",
			"marquis*",
			"baron*",
			"empereur",
			"impératrice",
			"pharaon",
			"sultan",
			"tsar",
			"monarque",
			"souverain*",
			"seigneur*",
			"aristocrate",
			"noble",
			"dynastie",
		],
	},
	{
		name: "Clergé",
		color: "#a8a29e",
		patterns: [
			"prélat",
			"évêque",
			"archevêque",
			"prêtre",
			"pape",
			"cardinal",
			"moine",
			"abbé",
			"pasteur",
			"rabbin",
			"imam",
			"missionnaire",
			"théologien*",
		],
	},
	{
		name: "Footballeurs",
		color: "#16a34a",
		patterns: ["footballeu*", "joueu* football", "joueu* soccer"],
	},
	{
		name: "Sportifs",
		color: "#fb923c",
		patterns: [
			"joueu*",
			"athlète*",
			"cycliste",
			"coureu*",
			"boxeu*",
			"nageu*",
			"biathlète*",
			"triathlète*",
			"hockeyeu*",
			"handballeu*",
			"basketteu*",
			"volleyeu*",
			"catcheu*",
			"patineu*",
			"skieu*",
			"golfeu*",
			"escrimeu*",
			"lutteu*",
			"rameu*",
			"judoka",
			"karatéka",
			"gymnaste",
			"alpiniste",
			"jockey",
			"tennisman",
			"tenniswoman",
			"rugbyman",
			"arbitre",
			"entraîneu*",
			"pilote automobile",
			"pilote moto*",
			"pilote course*",
			"pilote rallye",
		],
	},
	{
		name: "Acteurs & actrices",
		color: "#f472b6",
		patterns: ["acteu*", "actri*", "comédien*", "humoriste", "mannequin", "doubleu*", "cascadeu*"],
	},
	{
		name: "Cinéastes",
		color: "#ec4899",
		patterns: [
			"réalisateu*",
			"réalisatri*",
			"cinéaste",
			"scénariste",
			"producteu* cinéma",
			"producteu* film*",
			"productri* cinéma",
			"productri* film*",
		],
	},
	{
		name: "Musiciens",
		color: "#a78bfa",
		patterns: [
			"chanteu*",
			"cantatrice",
			"musicien*",
			"compositeu*",
			"compositri*",
			"auteur-compositeu*",
			"autrice-compositrice*",
			"pianiste",
			"guitariste",
			"violoniste",
			"violoncelliste",
			"organiste",
			"saxophoniste",
			"trompettiste",
			"batteu*",
			"bassiste",
			"rappeu*",
			"parolie*",
			"chef orchestre",
			"orchestre",
			"groupe musique",
			"groupe musical",
			"groupe rock",
			"groupe pop",
			"groupe punk",
			"groupe metal",
			"groupe métal",
			"groupe rap",
			"groupe hip-hop",
			"groupe jazz",
		],
	},
	{
		name: "Écrivains & journalistes",
		color: "#818cf8",
		patterns: [
			"écrivain*",
			"auteu*",
			"autrice",
			"poète",
			"poétesse",
			"romancie*",
			"dramaturge",
			"essayiste",
			"nouvelliste",
			"biographe",
			"journaliste",
			"chroniqueu*",
			"traducteu*",
			"traductri*",
		],
	},
	{
		name: "Peintres & artistes",
		color: "#e879f9",
		patterns: [
			"peintre",
			"artiste",
			"sculpteu*",
			"sculptri*",
			"photographe",
			"illustrateu*",
			"illustratri*",
			"dessinateu*",
			"dessinatri*",
			"bédéiste",
			"graveu*",
			"graphiste",
			"céramiste",
			"plasticien*",
			"designer",
			"styliste",
			"architecte",
		],
	},
	{
		name: "Scientifiques & intellectuels",
		color: "#2dd4bf",
		patterns: [
			"mathématicien*",
			"physicien*",
			"astrophysicien*",
			"chimiste",
			"biologiste",
			"botaniste",
			"zoologiste",
			"entomologiste",
			"naturaliste",
			"généticien*",
			"astronome",
			"médecin",
			"chirurgien*",
			"psychiatre",
			"psychologue",
			"neurologue",
			"pharmacien*",
			"vétérinaire",
			"virologue",
			"ingénieu*",
			"inventeu*",
			"informaticien*",
			"chercheu*",
			"universitaire",
			"professeu*",
			"historien*",
			"philosophe",
			"économiste",
			"sociologue",
			"linguiste",
			"géographe",
			"géologue",
			"archéologue",
			"anthropologue",
			"ethnologue",
			"paléontologue",
			"explorateu*",
			"exploratri*",
		],
	},
	{
		name: "Militaires",
		color: "#78716c",
		patterns: [
			"militaire",
			"général",
			"officier",
			"soldat",
			"amiral",
			"maréchal",
			"colonel",
			"capitaine",
			"lieutenant",
			"commandant",
			"résistant*",
			"aviateu*",
			"aviatri*",
			"guerrier",
			"mercenaire",
			"espion*",
		],
	},
	{
		name: "Personnalités",
		color: "#fda4af",
		patterns: [
			"personnalité",
			"personnage",
			"homme",
			"femme",
			"entrepreneu*",
			"avocat*",
			"juriste",
			"magistrat*",
			"juge",
			"militant*",
			"activiste",
			"aventurie*",
			"pionnie*",
			"animateu*",
			"animatrice",
			"présentateu*",
			"présentatrice",
			"vidéaste",
			"youtubeu*",
			"influenceu*",
			"cuisinie*",
			"banquie*",
			"industriel*",
			"philanthrope",
			"criminel*",
			"féministe",
			"concepteu*",
			"tueu*",
		],
	},
	{
		name: "Jeux",
		color: "#22d3ee",
		patterns: ["jeu vidéo", "jeu société", "jeu rôle", "jeu cartes", "jeu plateau", "jeu-vidéo"],
	},
	{
		name: "Livres & BD",
		color: "#c084fc",
		patterns: [
			"série bande dessiné*",
			"album bande dessiné*",
			"bande dessiné*",
			"livre",
			"roman",
			"manga",
			"comics",
			"poème",
			"recueil",
			"essai",
			"conte",
			"saga",
			"trilogie",
			"ouvrage",
			"encyclopédie",
			"dictionnaire",
			"magazine",
			"revue",
			"journal",
			"hebdomadaire",
			"périodique",
		],
	},
	{
		name: "Albums & chansons",
		color: "#8b5cf6",
		patterns: ["album", "chanson", "single", "morceau", "ep", "mixtape", "compilation", "hymne", "bande originale"],
	},
	{
		name: "Films & séries",
		color: "#f43f5e",
		patterns: [
			"saison série",
			"film",
			"téléfilm",
			"série",
			"web-série",
			"feuilleton",
			"sitcom",
			"telenovela",
			"documentaire",
			"court-métrage",
			"long-métrage",
			"métrage",
			"épisode",
			"émission",
			"anime",
			"dessin animé",
			"jeu télévisé",
			"chaîne télévision",
		],
	},
	{
		name: "Tableaux & sculptures",
		color: "#d946ef",
		patterns: [
			"tableau",
			"peinture",
			"sculpture",
			"fresque",
			"statue",
			"gravure",
			"estampe",
			"œuvre art",
			"oeuvre art",
		],
	},
	{
		name: "Clubs & compétitions",
		color: "#f97316",
		patterns: [
			"compétition",
			"championnat*",
			"coupe",
			"tournoi",
			"club",
			"équipe",
			"saison",
			"olympique*",
			"délégation",
			"course",
			"étape",
			"match",
			"rallye",
			"marathon",
			"ligue",
			"grand prix",
		],
	},
	{
		name: "Animaux",
		color: "#84cc16",
		patterns: [
			"étoile mer",
			"animal",
			"animaux",
			"oiseau*",
			"poisson*",
			"mammifère*",
			"reptile*",
			"amphibien*",
			"mollusque*",
			"gastéropode*",
			"crustacé*",
			"serpent*",
			"lézard*",
			"grenouille*",
			"tortue*",
			"requin*",
			"cétacé*",
			"rongeur*",
			"primate*",
			"chauve-souris",
			"dinosaure*",
			"vertébré*",
			"invertébré*",
			"méduse*",
			"corail",
			"coraux",
			"race",
		],
	},
	{
		name: "Insectes & araignées",
		color: "#a3e635",
		patterns: [
			"insecte*",
			"coléoptère*",
			"papillon*",
			"lépidoptère*",
			"diptère*",
			"hyménoptère*",
			"hémiptère*",
			"orthoptère*",
			"fourmi*",
			"abeille*",
			"guêpe*",
			"mouche*",
			"scarabée*",
			"libellule*",
			"punaise*",
			"moustique*",
			"araignée*",
			"arachnide*",
			"scorpion*",
			"acarien*",
			"myriapode*",
		],
	},
	{
		name: "Plantes & champignons",
		color: "#4ade80",
		patterns: [
			"plante*",
			"arbre*",
			"arbuste*",
			"algue*",
			"fougère*",
			"mousse*",
			"orchidée*",
			"graminée*",
			"conifère*",
			"cactus",
			"fleur*",
			"légume*",
			"fruit*",
			"céréale*",
			"cultivar*",
			"champignon*",
			"lichen*",
		],
	},
	{
		name: "Espace",
		color: "#60a5fa",
		patterns: [
			"station spatiale",
			"étoile",
			"planète",
			"comète",
			"cratère",
			"constellation",
			"astéroïde*",
			"galaxie*",
			"exoplanète*",
			"nébuleuse*",
			"météorite*",
			"satellite*",
			"lune",
			"pulsar",
			"quasar",
			"trou noir",
			"télescope",
			"spatial*",
			"fusée",
			"astronaute",
			"cosmonaute",
		],
	},
	{
		name: "Bâtiments & monuments",
		color: "#fbbf24",
		patterns: [
			"église",
			"chapelle",
			"cathédrale",
			"basilique",
			"abbaye",
			"monastère",
			"couvent",
			"prieuré",
			"temple",
			"mosquée",
			"synagogue",
			"sanctuaire",
			"château",
			"palais",
			"manoir",
			"villa",
			"fort",
			"forteresse",
			"citadelle",
			"musée",
			"bibliothèque",
			"monument",
			"mémorial",
			"édifice",
			"bâtiment",
			"immeuble",
			"gratte-ciel",
			"hôtel",
			"stade",
			"phare",
			"pont",
			"barrage",
			"cimetière",
			"tombe",
			"mausolée",
			"hôpital",
			"prison",
			"site archéologique",
			"résidence",
			"café",
			"restaurant",
		],
	},
	{
		name: "Transports",
		color: "#64748b",
		patterns: [
			"gare",
			"station",
			"aéroport",
			"port",
			"route",
			"autoroute",
			"rocade*",
			"rue",
			"avenue",
			"boulevard",
			"ligne",
			"tramway",
			"métro",
			"chemin fer",
			"tunnel",
			"canal",
			"navire",
			"bateau",
			"paquebot",
			"sous-marin",
			"avion",
			"locomotive",
			"train",
			"automobile",
			"voiture",
			"véhicule",
			"moto",
		],
	},
	{
		name: "Communes & villages",
		color: "#facc15",
		patterns: [
			"établissement humain",
			"commune",
			"village",
			"localité",
			"municipalité",
			"hameau",
			"bourg",
			"lieu-dit",
			"census-designated",
			"gmina",
			"paroisse",
			"intercommunalité",
			"kibboutz",
		],
	},
	{
		name: "Villes",
		color: "#f59e0b",
		patterns: ["ville", "capitale", "métropole", "agglomération", "banlieue", "quartier", "cité"],
	},
	{
		name: "Régions & pays",
		color: "#d97706",
		patterns: [
			"pays",
			"état",
			"région",
			"province",
			"département",
			"comté",
			"canton",
			"district",
			"arrondissement",
			"circonscription",
			"territoire",
			"colonie",
			"oblast",
			"voïvodie",
			"émirat",
			"royaume",
			"empire",
			"république",
			"principauté",
			"duché",
			"préfecture",
			"subdivision",
		],
	},
	{
		name: "Géographie",
		color: "#14b8a6",
		patterns: [
			"rivière",
			"fleuve",
			"ruisseau",
			"torrent",
			"affluent",
			"estuaire",
			"cascade",
			"lac",
			"lagune",
			"marais",
			"mer",
			"océan",
			"golfe",
			"baie",
			"détroit",
			"cap",
			"péninsule",
			"île",
			"îlot",
			"atoll",
			"archipel",
			"montagne",
			"mont",
			"massif",
			"sommet",
			"col",
			"volcan",
			"glacier",
			"colline",
			"plateau",
			"plaine",
			"vallée",
			"canyon",
			"falaise",
			"grotte",
			"désert",
			"forêt",
			"plage",
			"parc",
		],
	},
	{
		name: "Entreprises & organisations",
		color: "#0ea5e9",
		patterns: [
			"entreprise",
			"compagnie",
			"société",
			"firme",
			"marque",
			"constructeu*",
			"fabricant",
			"banque",
			"label",
			"studio",
			"maison édition",
			"maison disques",
			"organisation",
			"association",
			"fondation",
			"institution",
			"ong",
			"syndicat",
			"université",
			"école",
			"lycée",
			"collège",
			"institut",
		],
	},
	{
		name: "Histoire & événements",
		color: "#b45309",
		patterns: [
			"coup état",
			"bataille",
			"guerre",
			"siège",
			"révolution",
			"révolte",
			"conflit",
			"massacre",
			"attentat",
			"traité",
			"élection*",
			"événement*",
			"affaire",
			"accident",
			"catastrophe",
			"naufrage",
			"incendie",
			"séisme",
			"tremblement terre",
			"ouragan",
			"cyclone",
			"épidémie",
			"pandémie",
			"crise",
			"année",
			"mois",
			"siècle",
			"décennie",
			"millénaire",
		],
	},
	{
		name: "Langues & peuples",
		color: "#fb7185",
		patterns: ["langue", "dialecte", "alphabet", "peuple", "groupe ethnique", "ethnie", "tribu", "civilisation"],
	},
	{
		name: "Chimie",
		color: "#06b6d4",
		patterns: [
			"composé*",
			"molécule",
			"élément chimique",
			"isotope",
			"minéral",
			"minéraux",
			"roche",
			"alliage",
			"protéine",
			"enzyme",
			"gène",
			"hormone",
			"acide",
			"alcaloïde",
			"médicament",
		],
	},
	{
		name: "Noms & prénoms",
		color: "#e2e8f0",
		patterns: ["nom", "prénom", "surnom", "patronyme"],
	},
];

function tokenize(category: string): string[] {
	return category
		.toLowerCase()
		.split(/[^\p{L}-]+/u)
		.filter((token) => token.length > 0);
}

function singular(token: string): string {
	return token.replace(/[sx]$/, "");
}

function termMatches(term: string, token: string): boolean {
	if (term.endsWith("*")) return token.startsWith(term.slice(0, -1));
	return token === term || singular(token) === term;
}

function patternPosition(tokens: readonly string[], pattern: string): number | null {
	let firstPosition = Number.POSITIVE_INFINITY;
	for (const term of pattern.split(" ")) {
		const position = tokens.findIndex((token) => termMatches(term, token));
		if (position === -1) return null;
		firstPosition = Math.min(firstPosition, position);
	}
	return firstPosition;
}

function groupPosition(tokens: readonly string[], group: CategoryGroup): number | null {
	const positions = group.patterns.flatMap((pattern) => patternPosition(tokens, pattern) ?? []);
	return positions.length > 0 ? Math.min(...positions) : null;
}

export function categoryGroupOf(category: string): CategoryGroup | null {
	const tokens = tokenize(category);
	let best: { group: CategoryGroup; position: number } | null = null;
	for (const group of CATEGORY_GROUPS) {
		const position = groupPosition(tokens, group);
		if (position !== null && (best === null || position < best.position)) best = { group, position };
	}
	return best?.group ?? null;
}
