export interface CategoryGroup {
	name: string;
	color: string;
	words: readonly string[];
	stems: readonly string[];
}

export const CATEGORY_GROUPS: readonly CategoryGroup[] = [
	{
		name: "Homonymie",
		color: "#94a3b8",
		words: ["homonymie", "wikimédia", "wikimedia"],
		stems: [],
	},
	{
		name: "Espace",
		color: "#60a5fa",
		words: ["étoile", "planète", "comète", "cratère", "constellation"],
		stems: ["astéroïde", "galaxie", "exoplanète", "nébuleuse"],
	},
	{
		name: "Nature",
		color: "#4ade80",
		words: ["arbre", "algue", "oiseau", "poisson", "reptile", "papillon", "araignée", "bactérie", "mollusque"],
		stems: [
			"espèce",
			"plante",
			"insecte",
			"arachnide",
			"mammifère",
			"amphibien",
			"champignon",
			"crustacé",
			"coléoptère",
		],
	},
	{
		name: "Personnes",
		color: "#f472b6",
		words: [
			"homme",
			"femme",
			"roi",
			"reine",
			"prince",
			"princesse",
			"pape",
			"président",
			"présidente",
			"ministre",
			"député",
			"maire",
			"personnage",
			"humain",
			"humaine",
		],
		stems: [
			"joueu",
			"footballeu",
			"personnalité",
			"actri",
			"acteu",
			"cycliste",
			"peintre",
			"écrivain",
			"athlète",
			"politicien",
			"journaliste",
			"musicien",
			"chanteu",
			"compositeu",
			"compositri",
			"réalisateu",
			"réalisatri",
			"philosophe",
			"mannequin",
			"auteu",
			"autrice",
			"poète",
			"poétesse",
			"dramaturge",
			"sportif",
			"sportive",
			"entraîneu",
			"architecte",
			"sculpteu",
			"sculptrice",
			"photographe",
			"historien",
			"médecin",
			"ingénieu",
			"avocat",
			"prêtre",
			"évêque",
			"pilote",
			"boxeu",
			"nageu",
			"skieu",
			"tennisman",
			"tenniswoman",
			"rugbyman",
			"basketteu",
			"handballeu",
			"hockeyeu",
			"mathématicien",
			"physicien",
			"chimiste",
			"biologiste",
			"botaniste",
			"économiste",
			"sociologue",
			"militant",
			"producteu",
			"productri",
			"animateu",
			"animatrice",
			"humoriste",
			"comédien",
			"danseu",
			"rappeu",
			"guitariste",
			"pianiste",
			"violoniste",
			"diplomate",
			"officier",
			"aristocrate",
			"théologien",
			"linguiste",
			"illustrateu",
			"illustratrice",
			"dessinateu",
			"dessinatrice",
			"scénariste",
			"romancie",
			"essayiste",
			"traducteu",
			"traductri",
			"professeu",
			"universitaire",
			"chercheu",
			"inventeu",
			"entrepreneu",
			"empereu",
			"impératrice",
			"seigneu",
			"virologue",
			"pionnie",
			"résistant",
			"sénateu",
		],
	},
	{
		name: "Sport",
		color: "#fb923c",
		words: ["club", "équipe", "coupe", "saison", "tournoi"],
		stems: ["compétition", "championnat", "olympique"],
	},
	{
		name: "Œuvres",
		color: "#c084fc",
		words: [
			"film",
			"album",
			"chanson",
			"série",
			"roman",
			"livre",
			"téléfilm",
			"single",
			"émission",
			"opéra",
			"manga",
			"épisode",
			"jeu",
			"poème",
			"tableau",
			"sculpture",
			"documentaire",
			"court-métrage",
			"métrage",
			"magazine",
			"revue",
			"œuvre",
			"oeuvre",
			"ouvrage",
			"pièce",
			"bande",
			"nouvelle",
		],
		stems: [],
	},
	{
		name: "Lieux",
		color: "#facc15",
		words: [
			"commune",
			"village",
			"ville",
			"département",
			"comté",
			"rivière",
			"église",
			"région",
			"île",
			"montagne",
			"lac",
			"quartier",
			"gare",
			"château",
			"pays",
			"province",
			"municipalité",
			"localité",
			"district",
			"canton",
			"fleuve",
			"édifice",
			"monument",
			"cathédrale",
			"aéroport",
			"stade",
			"pont",
			"rue",
			"parc",
			"chapelle",
			"abbaye",
			"musée",
			"station",
			"hameau",
			"baie",
			"vallée",
			"col",
			"sommet",
			"plage",
			"port",
			"arrondissement",
			"capitale",
			"archipel",
			"désert",
			"forêt",
			"basilique",
			"temple",
			"mosquée",
			"palais",
			"route",
			"autoroute",
			"ligne",
			"état",
			"territoire",
			"oblast",
			"gmina",
			"voïvodie",
			"paroisse",
			"bâtiment",
			"immeuble",
			"phare",
			"barrage",
			"canal",
			"mer",
			"océan",
			"golfe",
			"cap",
			"péninsule",
			"volcan",
			"glacier",
			"grotte",
			"cimetière",
			"école",
			"université",
			"lycée",
			"hôpital",
			"prison",
			"colonie",
			"émirat",
			"fort",
			"intercommunalité",
			"circonscription",
			"banlieue",
			"agglomération",
			"métropole",
			"cité",
		],
		stems: [],
	},
];

function tokenize(category: string): string[] {
	return category
		.toLowerCase()
		.split(/[^\p{L}-]+/u)
		.filter((token) => token.length > 0);
}

function singular(token: string): string {
	return token.replace(/[sx]$/, "");
}

function matchesGroup(tokens: readonly string[], group: CategoryGroup): boolean {
	return tokens.some(
		(token) =>
			group.words.includes(token) ||
			group.words.includes(singular(token)) ||
			group.stems.some((stem) => token.startsWith(stem)),
	);
}

export function categoryGroupOf(category: string): CategoryGroup | null {
	const tokens = tokenize(category);
	return CATEGORY_GROUPS.find((group) => matchesGroup(tokens, group)) ?? null;
}
